---
title: "Statistical Methods for Data Analysis (2025 Fall, Hanyang University)"
---

## About this course

-   Course name: MAT2033 (11778/13018), Statistical Methods for Data Analysis

-   Instructor: [Seoncheol Park](https://seoncheolpark.github.io)

-   TA: Minseok Choi

-   Language: English

-   Schedule: 
    -   For 11778: TUE 10:30-12:00, FRI 13:00-14:30 (Room 222, Building 507)
    -   For 13018: TUE 13:00-14:30, FRI 10:30-12:00

-   Textbook:

    -   [A First Course in Statistical Programming with R](https://product.kyobobook.co.kr/detail/S000003105779)
    -   [R 통계 프로그래밍 교과서](https://product.kyobobook.co.kr/detail/S000001892788)

-   Grading:

    -   Class attendance (10%)
    -   In-class exercises (30%)
    -   Midterm (30%)
    -   Final (30%)

## Notice for Students Who Have Already Taken `Statistical Computing` (MAT2021)

- The course **`Statistical Methods for Data Analysis`** has been **newly introduced in 2025** to replace **`Statistical Computing`**.  
- However, due to an **administrative oversight**, it has not yet been designated as a replacement course.  
  + As a result, students who have previously taken **`Statistical Computing`** may also enroll in **`Statistical Methods for Data Analysis`** **this year (2025)**.  
  + At present, this issue cannot be resolved, so students who completed **`Statistical Computing`** **cannot retake** it as **`Statistical Methods for Data Analysis`** in 2025.
  + From **2026**, however, it will be officially designated as the replacement course.  
- Students who have taken **`Statistical Computing`** are advised to note that the contents of **`Statistical Methods for Data Analysis`** are **largely similar** to those of **`Statistical Computing`** when registering for the course.  
- For **fairness with other students**, those who have already taken **`Statistical Computing`** will be **graded separately** from those who have not.  


### (Korean translated ver.)

- `Statistical Methods for Data Analysis` 과목은 `Statistical Computing`을 대체하기 위해 2025년도부터 신설한 과목입니다.
- 그러나 행정적 실수로 인해 대체과목으로 지정이 안되어 있어, `Statistical Computing` 과목을 들은 학생도 올해는 `Statistical Methods for Data Analysis` 과목을 수강할 수 있습니다. 현재 이를 해결할 수는 없어 `Statistical Computing` 과목을 들은 학생이 올해 `Statistical Methods for Data Analysis` 과목으로 재수강할 수는 없으나, 2026년부터는 대체과목으로 지정할 예정입니다.
- `Statistical Computing` 과목을 들은 학생들은 과목 `Statistical Methods for Data Analysis` 과목 컨텐츠가 `Statistical Computing` 과목과 유사함에 유의하여 수강신청 하시기 바랍니다.
- 다른 학생들과의 형평성을 위해 `Statistical Computing` 과목을 들은 학생들은 그렇지 않은 학생들과 분리하여 별도로 grading을 할 것입니다.